# ConfigMap for non-secret environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: codecourt-config
  namespace: codecourt
data:
  PORT: "5000"
  NODE_ENV: "production"
  REDIS_URL: "redis://redis-service:6379"
  AI_SERVICE_URL: "https://ofxvp2pj3b.execute-api.us-east-1.amazonaws.com"
  FRONTEND_URL: "https://d1cndb5oyhrmuc.cloudfront.net"
  CORS_ORIGINS: "http://localhost:3000,https://d1cndb5oyhrmuc.cloudfront.net"

  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "codecourt-test-cases-bucket"
  K8S_NAMESPACE: "codecourt"
  USE_LOCAL_STORAGE: "false"
