// PROJECT_STATUS.md generator
// Parses tasks.md and generates a status report

const fs = require('fs');
const path = require('path');

function generateStatus() {
  try {
    const tasksPath = path.join(__dirname, '../.kiro/specs/codecourt-mvp/tasks.md');
    const tasksContent = fs.readFileSync(tasksPath, 'utf-8');

    // Parse tasks and count completion
    const lines = tasksContent.split('\n');
    let totalTasks = 0;
    let completedTasks = 0;
    let inProgressTasks = 0;

    lines.forEach(line => {
      if (line.match(/^- \[x\]/)) {
        completedTasks++;
        totalTasks++;
      } else if (line.match(/^- \[-\]/)) {
        inProgressTasks++;
        totalTasks++;
      } else if (line.match(/^- \[ \]/)) {
        totalTasks++;
      }
    });

    const completionPercentage = totalTasks > 0 
      ? ((completedTasks / totalTasks) * 100).toFixed(1)
      : 0;

    // Generate PROJECT_STATUS.md
    const statusContent = `# CodeCourt MVP - Project Status

**Last Updated:** ${new Date().toISOString().split('T')[0]}

## Overall Progress

- **Total Tasks:** ${totalTasks}
- **Completed:** ${completedTasks} (${completionPercentage}%)
- **In Progress:** ${inProgressTasks}
- **Remaining:** ${totalTasks - completedTasks - inProgressTasks}

## Phase Status

### Phase 0: Prerequisites & Setup
Status: In Progress

### Phase 1: Folder Structure & Dependencies
Status: In Progress

### Phase 2: Core Backend Implementation
Status: Not Started

### Phase 3: AI Service Implementation
Status: Not Started

### Phase 4: Frontend Implementation
Status: Not Started

### Phase 5: Redis Caching Integration
Status: Not Started

### Phase 6: Documentation & Tooling
Status: Not Started

### Phase 7: Docker Compose
Status: Not Started

### Phase 8: Production Dockerfiles
Status: Not Started

### Phase 9: CI/CD Pipeline
Status: Not Started

### Phase 10: Kubernetes Manifests
Status: Not Started

### Phase 11: Terraform Infrastructure
Status: Not Started

### Phase 12: Production Deployment
Status: Not Started

### Phase 13: Final Polish & Documentation
Status: Not Started

### Phase 14: Resume Preparation
Status: Not Started

---

*This file is auto-generated by scripts/generate-status.js*
`;

    const outputPath = path.join(__dirname, '../PROJECT_STATUS.md');
    fs.writeFileSync(outputPath, statusContent);
    console.log('✅ PROJECT_STATUS.md generated successfully');

  } catch (error) {
    console.error('❌ Error generating status:', error);
    process.exit(1);
  }
}

generateStatus();
