// Agent controller - proxy to AI service
const axios = require('axios');
const Hint = require('./model');

const AI_SERVICE_URL = process.env.AI_SERVICE_URL || 'http://localhost:8000';

/**
 * Proxy hint request to FastAPI AI service
 * POST /api/agent/hint
 */
exports.getHint = async (req, res, next) => {
  try {
    const { problem_id, problem_slug } = req.body;
    const user_id = req.user.id;
    
    // Forward request to AI service
    const response = await axios.post(`${AI_SERVICE_URL}/hint`, {
      user_id,
      problem_id,
      problem_slug
    });
    
    res.json(response.data);
  } catch (error) {
    if (error.response) {
      // Forward error from AI service
      return res.status(error.response.status).json(error.response.data);
    }
    next(error);
  }
};

/**
 * Get hint count for (user, problem) pair
 * GET /api/agent/hint-count?user_id=...&problem_id=...
 * 
 * This endpoint returns how many hints a specific user has already
 * generated for a specific problem. Used by the AI service to enforce
 * the 3-hint limit per user per problem.
 */
exports.getHintCount = async (req, res, next) => {
  try {
    const { user_id, problem_id } = req.query;
    
    // Validate required query parameters
    if (!user_id || !problem_id) {
      return res.status(400).json({ 
        error: 'Missing required query parameters: user_id and problem_id' 
      });
    }
    
    // Query MongoDB to count how many Hint documents exist
    // for this specific (userId, problemId) combination
    // This uses Mongoose's countDocuments() method which is optimized
    // for counting without loading the actual documents into memory
    const count = await Hint.countDocuments({ 
      userId: user_id, 
      problemId: problem_id 
    });
    
    // Return the count in a JSON response
    res.json({ 
      hint_count: count,
      user_id,
      problem_id
    });
  } catch (error) {
    // Pass any database errors to the global error handler middleware
    next(error);
  }
};

/**
 * Get previously generated hints for a user/problem pair.
 * Called by the AI service so the next hint can avoid repeating earlier ones.
 */
exports.getHints = async (req, res, next) => {
  try {
    const { user_id, problem_id } = req.query;

    if (!user_id || !problem_id) {
      return res.status(400).json({
        error: 'Missing required query parameters: user_id and problem_id'
      });
    }

    const hints = await Hint.find({
      userId: user_id,
      problemId: problem_id
    })
      .sort({ hintIndex: 1, createdAt: 1 })
      .lean();

    res.json({
      count: hints.length,
      hints: hints.map(hint => ({
        id: hint._id,
        hintText: hint.hintText,
        hintIndex: hint.hintIndex,
        createdAt: hint.createdAt
      }))
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Get hints for the authenticated user/problem pair.
 * Used by the frontend to show already-used hints instead of a dead-end error.
 */
exports.getMyHints = async (req, res, next) => {
  try {
    const { problem_id } = req.query;
    const user_id = req.user.id;

    if (!problem_id) {
      return res.status(400).json({
        error: 'Missing required query parameter: problem_id'
      });
    }

    const hints = await Hint.find({
      userId: user_id,
      problemId: problem_id
    })
      .sort({ hintIndex: 1, createdAt: 1 })
      .lean();

    res.json({
      count: hints.length,
      hints_used: hints.length,
      hints_remaining: Math.max(0, 3 - hints.length),
      hints: hints.map(hint => ({
        id: hint._id,
        hintText: hint.hintText,
        hintIndex: hint.hintIndex,
        createdAt: hint.createdAt
      }))
    });
  } catch (error) {
    next(error);
  }
};

/**
 * Save hint and increment count
 * POST /api/agent/save-hint
 * 
 * This endpoint persists a newly generated hint into the database.
 * It enforces the 3-hint limit per user per problem.
 * 
 * Request body:
 * - user_id: MongoDB ObjectId of the user
 * - problem_id: String identifier of the problem
 * - hint_text: The hint content generated by the AI
 * 
 * Returns:
 * - 201: Hint saved successfully with hint data
 * - 400: Missing required fields
 * - 403: User has already reached the 3-hint limit
 */
exports.saveHint = async (req, res, next) => {
  try {
    const { user_id, problem_id, hint_text } = req.body;
    
    // Validate required fields
    if (!user_id || !problem_id || !hint_text) {
      return res.status(400).json({ 
        error: 'Missing required fields: user_id, problem_id, and hint_text are required' 
      });
    }
    
    // Count existing hints for this user/problem combination
    // This determines the hintIndex for the new hint
    const existingHintCount = await Hint.countDocuments({ 
      userId: user_id, 
      problemId: problem_id 
    });
    
    // Enforce the 3-hint limit per user per problem
    // If the user already has 3 hints, reject the request
    if (existingHintCount >= 3) {
      return res.status(403).json({ 
        error: 'Hint limit reached',
        message: 'You have already used all 3 hints for this problem',
        hints_used: existingHintCount,
        max_hints: 3
      });
    }
    
    // Calculate the new hint index (1-based indexing)
    // If they have 0 hints, new index is 1
    // If they have 1 hint, new index is 2, etc.
    const newHintIndex = existingHintCount + 1;
    
    // Create and save the new Hint document in MongoDB
    const hint = await Hint.create({
      userId: user_id,
      problemId: problem_id,
      hintText: hint_text,
      hintIndex: newHintIndex
    });
    
    // Return success response with the saved hint data
    res.status(201).json({ 
      message: 'Hint saved successfully',
      hint: {
        id: hint._id,
        userId: hint.userId,
        problemId: hint.problemId,
        hintText: hint.hintText,
        hintIndex: hint.hintIndex,
        createdAt: hint.createdAt
      },
      hints_used: newHintIndex,
      hint_index: newHintIndex,
      hints_remaining: 3 - newHintIndex
    });
  } catch (error) {
    // Pass any database errors to the global error handler middleware
    next(error);
  }
};

/**
 * Get submission history for AI service
 * GET /api/agent/submissions?user_id=...&problem_id=...
 * 
 * Called internally by the AI service to fetch user submissions.
 */
exports.getSubmissionHistory = async (req, res, next) => {
  try {
    const { user_id, problem_id } = req.query;
    
    if (!user_id || !problem_id) {
      return res.status(400).json({ 
        error: 'Missing required query parameters: user_id and problem_id' 
      });
    }

    // Require the Submission model dynamically or add to top
    const Submission = require('../submissions/model');

    const submissions = await Submission.find({ 
      userId: user_id, 
      problemId: problem_id 
    }).sort({ createdAt: -1 });

    res.json({
      count: submissions.length,
      submissions: submissions.map(sub => ({
        verdict: sub.verdict,
        executionTime: sub.executionTime,
        memoryUsed: sub.memoryUsed,
        compilerError: sub.compilerError,
        createdAt: sub.createdAt
      }))
    });
  } catch (error) {
    next(error);
  }
};
